# @package _global_

defaults:
  - _self_

env:
  _target_: EasyNCO.methods.envs.ATSPEnv
  problem_size: 100
  pomo_size: 100 # same as node_cnt
  seed: 0
  aug_factor: 128

model:
  _target_: EasyNCO.methods.operators.neural_operators.ATSPPolicy
  embedding_dim: 256
  num_heads: 16
  qkv_dim: 16
  num_encoder_layers: 5
  feedforward_hidden: 512
  logit_clipping: 10.0
  one_hot_seed_cnt: 100 # must be >= node_cnt
  ms_hidden_dim: 16
  #! can't input the following parameters
  # ms_layer1_init: (1 / 2) ** (1 / 2)
  # ms_layer2_init: (1 / 16) ** (1 / 2)

module:
  _target_: EasyNCO.phases.train.rl.REINFORCELightning
  baseline: "shared"
  problem_size: ${env.problem_size}
  batch_size: 100
  episodes: 100
  first_mode: "random"
  optimizer_type: "Adam"
  scheduler_type: "MultiStepLR"
  optimizer_params: {
      "optimizer": { "lr": 4e-4, "weight_decay": 1e-6 },
      "scheduler": { "gamma": 0.1, "milestones": [2001, 2101] },
    } # if further training is needed,
  test_strategy: "sampling"
  aug_factor: ${env.aug_factor}
  train_data_params: { "int_min": 0, "int_max": 1000000, "scaler": 1000000 }

logger:
  _target_: lightning.pytorch.loggers.TensorBoardLogger
  save_dir: "tensorboard_log/"
  name: null
  log_graph: False
  default_hp_metric: True
  prefix: ""

model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: "checkpoints_debug/"
  filename: "am-{epoch:02d}"
  save_top_k: -1 # save all checkpoints
  every_n_epochs: 1 # save it every epoch

trainer:
  _target_: EasyNCO.phases.train.rl.RLTrainer
  max_epochs: 5
  reload_dataloaders_every_n_epochs: 1
  log_every_n_steps: 1
  accelerator: "gpu"
  num_nodes: 1 # Number of gpu nodes for distributed training

test_loader:
  model_dirpath: "/methods/operators/neural_operators/matnet/pretrained/atsp100/"
  model_filename: "epoch-12000.pt"
  data_path: "/data/datasets/atsp/n100.pt"
