# https://hydra.cc/docs/configure_hydra/intro/
env:
  _target_: EasyNCO.neural_solvers.envs.FJSPEnv
#  problem_size: ${scale}  #job×machine
  num_job: ${num_job}
  num_machine: ${num_machine}
  method_name: ${model}
  test_strategy: ${decoder_strategy}
  num_sample: 100  #In drl-hgnn,sampling means contains multiple (=num_sample) copies of one instance

model:
  _target_: EasyNCO.neural_solvers.methods.DRL_HGNNPolicy
  in_size_ma: 3
  out_size_ma: 8
  in_size_ope: 6
  out_size_ope: 8
  hidden_size_ope: 128
  n_latent_actor: 64
  n_latent_critic: 64
  n_hidden_actor: 3
  n_hidden_critic: 3
  action_dim: 1
  num_heads: [1,1]
  dropout: 0.0


initialization:
  _target_: EasyNCO.neural_solvers.methods.DRL_HGNNInitialization

iteration:
  _target_: EasyNCO.neural_solvers.pipeline.NoIteration


module:
  _target_: EasyNCO.phases.ARREINFORCELightning #
  method_name: ${model}
  baseline: 'shared'
  problem_size: ${scale}
  num_job: ${num_job}
  num_machine: ${num_machine}
  batch_size: ${batch_size}
  episodes: ${episodes}
  optimizer_type: 'Adam' # 'Adam', 'AdamW'
  scheduler_type: null #'ExponentialLR', 'MultiStepLR'
  optimizer_params: {
    'optimizer': {
        'lr': 0.0002,
#        'weight_decay': 1e-6
    },
#    'scheduler': {
#        'milestones': [501,],
#        'gamma': 0.1
#    }
  }
  decoder_strategy: ${decoder_strategy}
  every_n_steps_output: 2 # output log every n steps (i.e., batch)



model_checkpoint:
  #_target_: lightning.pytorch.callbacks.ModelCheckpoint
  _target_: EasyNCO.utils.utils.CustomModelCheckpoint
  dirpath: checkpoints
  filename: ${model}_${problem}$${num_job}×{num_machine}_{epoch:02d}
  save_top_k: ${save_top_k}
  every_n_epochs: ${every_n_epochs}

trainer:
  _target_: lightning.pytorch.Trainer
  max_epochs: ${max_epochs} # max epochs
  reload_dataloaders_every_n_epochs: 1 # RL: 1, SL: 0
  log_every_n_steps: ${log_every_n_steps} # log every n steps
  precision: ${precision}
  enable_progress_bar: ${enable_progress_bar} # disable progress bar
#  gradient_clip_val: 1.0

test_loader:
  model_dirpath: pretrained    #./results/train/pomo_cvrp/2025-05-21-10-05-48_pomo_cvrp_100_train
  model_filename: drl_hgnn_fjsp_10_5.ckpt                     #${model}_${problem}${scale}_epoch=04.ckpt
