# https://hydra.cc/docs/configure_hydra/intro/
env:
  _target_: EasyNCO.neural_solvers.envs.CVRPEnv #
  problem_size: ${scale}  #omni train in diverse sizes [50,200]
  pomo_size: ${scale}
  aug_type: pomo_aug # 'pomo_aug' or 'invit_aug'
  aug_factor: 8

model:
  _target_: EasyNCO.neural_solvers.methods.OMNI_POMO_Policy
  env_name: ${problem}
  num_heads: 8
  qkv_dim: 16
  num_encoder_layers: 6
  normalization: 'batch_no_track' # 'batch', 'layer', 'instance' ,'batch_no_track'or null (i.e., None)
  feedforward_hidden: 512
  logit_clipping: 10
  use_graph_mean: False
  am_mode: False
  first_placeholder: False
  first_mode: 'random' # random or placeholder


initialization:
  _target_: EasyNCO.neural_solvers.methods.OMNIInitialization

fine_tune_initialization:
  _target_: EasyNCO.neural_solvers.methods.POMOInitialization

iteration:
  _target_: EasyNCO.neural_solvers.pipeline.NoIteration

module:
  _target_: EasyNCO.phases.ARREINFORCELightning #
  method_name: ${model}
  baseline: 'shared'
  problem_size: ${scale}
  batch_size: ${batch_size}
  episodes: ${episodes}
  aug_type: 'pomo_aug' # 'pomo_aug' or 'invit_aug'
  optimizer_type: 'Adam' # 'Adam', 'AdamW'
  scheduler_type: null #'ExponentialLR', 'MultiStepLR'
  optimizer_params: {
    'optimizer': {
        'lr': 1e-4,
        'weight_decay': 1e-6
    },
#    'scheduler': {
#        'milestones': [501,],
#        'gamma': 0.1
#    }
  }
  decoder_strategy: ${decoder_strategy}
  every_n_steps_output: 2 # output log every n steps (i.e., batch)
  mode: ${mode} #train/eav
  fine_tune:
    'enable': False
    'fine_tune_episodes': 1000 # how many data used to fine-tune the pretrained model
    'k': 1  # fine-tune steps/epochs
    'augmentation_enable': False
    'fine_tune_batch_size': 10 # the batch size of the inner-loop optimization
    'optimizer': {
      'lr': 1e-5 ,
      'weight_decay': 1e-6
    }
  initialization_params: {
    meta_params: {
      'meta_method': 'maml_fomaml',  # choose from ['maml', 'fomaml', 'maml_fomaml']
      'data_type': 'size_distribution',  # choose from ["size", "distribution", "size_distribution"]
      'switch_epochs': 50000,  # switch from maml to fomaml
      'B': 1,  # the number of tasks in a mini-batch
      'k': 1,  # gradient decent steps in the inner-loop optimization of meta-learning method
      'meta_batch_size': 64,  # will be divided by 2 if problem_size >= 150
      'update_weight': 100,  # update weight of each task per X iters
      'sch_epoch': 225000,  # for the task scheduler of size setting, where sch_epoch = 0.9 * epochs
      'solver': 'lkh3_offline',  # solver used to update the task weights, choose from ["lkh3_online", "lkh3_offline"]
      'beta': 0.9,  # loss weight
    }
  }



model_checkpoint:
  #_target_: lightning.pytorch.callbacks.ModelCheckpoint
  _target_: EasyNCO.utils.utils.CustomModelCheckpoint
  dirpath: checkpoints
  filename: ${model}_${problem}${scale}_{epoch:02d}
  save_top_k: ${save_top_k}
  every_n_epochs: ${every_n_epochs}

trainer:
  _target_: lightning.pytorch.Trainer
  max_epochs: ${max_epochs} # max epochs
  reload_dataloaders_every_n_epochs: 1 # RL: 1, SL: 0
  log_every_n_steps: ${log_every_n_steps} # log every n steps
  precision: ${precision}
  enable_progress_bar: ${enable_progress_bar} # disable progress bar
#  gradient_clip_val: 1.0

test_loader:
  model_dirpath: pretrained
  model_filename: ${model}_${problem}_maml_fomaml.ckpt
