# @package _global_


defaults:
  - _self_

env50:
  _target_: EasyNCO.methods.envs.ASHPPEnv
  problem_size: 50
  pomo_size: 500


revision_model:
  _target_: EasyNCO.methods.operators.neural_operators.matnetPolicy
  embedding_dim: 256
  num_heads: 16
  qkv_dim: 16
  num_encoder_layers: 5
  feedforward_hidden: 512
  logit_clipping: 10.0
  one_hot_seed_cnt: 50
  ms_hidden_dim: 16
  ms_layer1_init: 0.7071067811865476
  ms_layer2_init: 0.25




module:
  _target_: EasyNCO.phases.train.rl.REINFORCELightning
  baseline: 'shared'
  problem_size: 250
  batch_size: 1
  episodes: 30
  first_mode: 'random'
  test_strategy: "sampling"
  model_name: "glop"
  glop_params: {
              main_problem: "ATSP",
              revision_lens: [50],
              iter: [3],
  }
  optimizer_params: {'optimizer': {
        'lr': 1e-4,
        'weight_decay': 1e-6
    },
#    'scheduler': {
#        'milestones': [501,],
#        'gamma': 0.1
#    }
  }

#The most important hyperparameter to use is `reload_dataloaders_every_n_epochs`.
#This allows for datasets to be re-created on the run and distributed by Lightning across
#devices on each epoch. Setting to a value different than 1 may lead to overfitting to a
#specific (such as the initial) data distribution.
trainer:
  _target_: EasyNCO.phases.train.rl.RLTrainer
  max_epochs: 5
  reload_dataloaders_every_n_epochs: 1
  log_every_n_steps: 1
  accelerator: 'gpu'
  num_nodes: 1 # Number of gpu nodes for distributed training


# https://www.tensorflow.org/tensorboard/
#Solve the error: ImportError: cannot import name ‘notf‘ from ‘tensorboard.compat‘
#Solution: Uninstall tensorflow and tensorboard(including all affiliated libraries)
# and only install tensorboard if you are using pytorch.
logger:
  _target_: lightning.pytorch.loggers.TensorBoardLogger
  save_dir: "tensorboard_log/"
  name: null
  log_graph: False
  default_hp_metric: True
  prefix: ""


model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: 'checkpoints_debug/'
  filename: 'glop_test_atsp-{epoch:02d}'
  save_top_k: -1 # 保存所有检查点
  every_n_epochs: 1 # 每1轮保存一次,

test_loader:
  revision_path: {
                    re100_path: "/pretrain/glop_matnet/matnet_ashpp_100.pth",
                    re50_path: "/pretrain/glop_matnet/matnet_ashpp_50.pth",
                    re20_path: "/pretrain/glop_matnet/matnet_ashpp_20.pth"
  }
  data_path: "/data/glop_test_data/atsp/ATSP250.pt"

