# python train.py settings=deepaco_settings mode=train problem=tsp
# python train.py settings=deepaco_settings mode=train problem=cvrp
# python train.py settings=deepaco_settings mode=train problem=op settings.model.feats=2 settings.model.phe_net=True
# python train.py settings=deepaco_settings mode=train problem=pctsp settings.model.feats=2 settings.model.phe_net=True
# python train.py settings=deepaco_settings mode=train problem=sop settings.model.phe_net=True settings.model.update_x=False
# python train.py settings=deepaco_settings mode=train problem=smtwtp settings.model.feats=2 settings.model.phe_net=True settings.model.update_x=False
# python train.py settings=deepaco_settings mode=train problem=rcpsp settings.model.feats=5 settings.model.edge_feats=2
# python train.py settings=deepaco_settings mode=train problem=mkp settings.model.feats=5 settings.model.phe_net=True
# python train.py settings=deepaco_settings mode=train problem=bpp

env:
  _target_: EasyNCO.neural_solvers.envs.TSPEnv
  problem_size: ${scale}
  pomo_size: ${scale}
  aug_type: pomo_aug # 'pomo_aug' or 'invit_aug'
  aug_factor: 8

model:
  _target_: EasyNCO.neural_solvers.backbones.GNN.net.Net
  feats: 1
  edge_feats: 1
  phe_net: False
  update_x: True

initialization:
  _target_: EasyNCO.neural_solvers.methods.DeepACOInitialization

iteration:
  _target_: EasyNCO.neural_solvers.methods.DeepACOIteration

module:
  _target_: EasyNCO.phases.ARREINFORCELightning
  method_name: ${model}
  baseline: 'no'
  problem_size: ${scale}
  batch_size: ${batch_size}
  episodes: ${episodes}
  val_episode: ${val_episode}
  optimizer_type: 'Adam' # 'Adam', 'AdamW'
  scheduler_type: null #'ExponentialLR', 'MultiStepLR'
  optimizer_params: {
    'optimizer': {
        'lr': 1e-4,
        'weight_decay': 1e-6
    },
#    'scheduler': {
#        'milestones': [501,],
#        'gamma': 0.1
#    }
  }
  decoder_strategy: ${decoder_strategy}
  every_n_steps_output: 100 # output log every n steps (i.e., batch)
  iteration_params:
    max_steps: 10
    problem_type: ${problem}
    policy_param: {
              'model_name': 'GNN',
              'n_ants': 20,
              'decay': 0.9,
              'alpha': 1,
              'beta': 1,
              'elitist': False,
              'min_max': False,
              'min': null,
              'two_opt': False, # tsp
              'local_search': 'nls', # tsp
              'k_sparse': null, # tsp, pctsp
              'adaptive': False, # cvrp
              'swapstar': False, # cvrp
              }
  


model_checkpoint:
  #_target_: lightning.pytorch.callbacks.ModelCheckpoint
  _target_: EasyNCO.utils.utils.CustomModelCheckpoint
  dirpath: checkpoints
  filename: ${model}_${problem}${scale}_{epoch:02d}
  save_top_k: ${save_top_k}
  every_n_epochs: ${every_n_epochs}

trainer:
  _target_: lightning.pytorch.Trainer
  max_epochs: ${max_epochs} # max epochs
  reload_dataloaders_every_n_epochs: 1 # RL: 1, SL: 0
  log_every_n_steps: ${log_every_n_steps} # log every n steps
  precision: ${precision}
  enable_progress_bar: ${enable_progress_bar} # disable progress bar
  gradient_clip_val: 1.0

test_loader:
  model_dirpath: pretrained
  model_filename: deepaco_tsp100_nls.ckpt