#!/usr/bin/env bash
set -euo pipefail

(cd /public/home/zhoucl/shiys/EasyNCO && python eval.py settings=matnet_settings mode=test model=matnet problem=atsp scale=20 batch_size=4 episodes=2500 decoder_strategy=greedy 'cuda=[0]' test_data_path=offline_init_v3/atsp/atsp20_nums2500.pt settings.test_loader.model_dirpath=pretrained/matnet_pretrain settings.test_loader.model_filename=matnet_atsp20.ckpt dir=results/label_v3/matnet_atsp/scale_20 settings.env.pomo_size=20 settings.module.initialization_params.pomo_size=20)
(cd /public/home/zhoucl/shiys/EasyNCO && python eval.py settings=matnet_settings mode=test model=matnet problem=atsp scale=50 batch_size=4 episodes=3500 decoder_strategy=greedy 'cuda=[0]' test_data_path=offline_init_v3/atsp/atsp50_nums3500.pt settings.test_loader.model_dirpath=pretrained/matnet_pretrain settings.test_loader.model_filename=matnet_atsp50.ckpt dir=results/label_v3/matnet_atsp/scale_50)
(cd /public/home/zhoucl/shiys/EasyNCO && python eval.py settings=matnet_settings mode=test model=matnet problem=atsp scale=100 batch_size=4 episodes=4000 decoder_strategy=greedy 'cuda=[0]' test_data_path=offline_init_v3/atsp/atsp100_nums4000.pt settings.test_loader.model_dirpath=pretrained/matnet_pretrain settings.test_loader.model_filename=matnet_atsp100.ckpt dir=results/label_v3/matnet_atsp/scale_100)
(cd /public/home/zhoucl/shiys/EasyNCO && python eval.py settings=matpoenet_settings mode=test model=matpoenet problem=atsp scale=20 batch_size=4 episodes=2500 decoder_strategy=greedy 'cuda=[0]' test_data_path=offline_init_v3/atsp/atsp20_nums2500.pt settings.test_loader.model_dirpath=pretrained/matpoenet settings.test_loader.model_filename=MatNet-POE_mix.pt dir=results/label_v3/matpoenet_atsp/scale_20)
(cd /public/home/zhoucl/shiys/EasyNCO && python eval.py settings=matpoenet_settings mode=test model=matpoenet problem=atsp scale=50 batch_size=4 episodes=3500 decoder_strategy=greedy 'cuda=[0]' test_data_path=offline_init_v3/atsp/atsp50_nums3500.pt settings.test_loader.model_dirpath=pretrained/matpoenet settings.test_loader.model_filename=MatNet-POE_mix.pt dir=results/label_v3/matpoenet_atsp/scale_50)
(cd /public/home/zhoucl/shiys/EasyNCO && python eval.py settings=matpoenet_settings mode=test model=matpoenet problem=atsp scale=100 batch_size=4 episodes=4000 decoder_strategy=greedy 'cuda=[0]' test_data_path=offline_init_v3/atsp/atsp100_nums4000.pt settings.test_loader.model_dirpath=pretrained/matpoenet settings.test_loader.model_filename=MatNet-POE_mix.pt dir=results/label_v3/matpoenet_atsp/scale_100)
(cd /public/home/zhoucl/shiys/EasyNCO && python eval.py settings=glop_settings mode=test model=glop problem=atsp scale=20 batch_size=1 episodes=2500 decoder_strategy=greedy 'cuda=[0]' test_data_path=offline_init_v3/atsp/atsp20_nums2500.pt settings.test_loader.model_dirpath=pretrained/glop settings.test_loader.model_filename=glop_policy_atsp.pt dir=results/label_v3/glop_atsp/scale_20 settings.iteration._target_=EasyNCO.neural_solvers.pipeline.NoIteration)
(cd /public/home/zhoucl/shiys/EasyNCO && python eval.py settings=glop_settings mode=test model=glop problem=atsp scale=50 batch_size=1 episodes=3500 decoder_strategy=greedy 'cuda=[0]' test_data_path=offline_init_v3/atsp/atsp50_nums3500.pt settings.test_loader.model_dirpath=pretrained/glop settings.test_loader.model_filename=glop_policy_atsp.pt dir=results/label_v3/glop_atsp/scale_50 settings.iteration._target_=EasyNCO.neural_solvers.pipeline.NoIteration)
(cd /public/home/zhoucl/shiys/EasyNCO && python eval.py settings=glop_settings mode=test model=glop problem=atsp scale=100 batch_size=1 episodes=4000 decoder_strategy=greedy 'cuda=[0]' test_data_path=offline_init_v3/atsp/atsp100_nums4000.pt settings.test_loader.model_dirpath=pretrained/glop settings.test_loader.model_filename=glop_policy_atsp.pt dir=results/label_v3/glop_atsp/scale_100 settings.iteration._target_=EasyNCO.neural_solvers.pipeline.NoIteration)
