# @package _global_

defaults:
  - _self_

model:
  _target_: EasyNCO.methods.backbones.GNN.net.Net

module:
  _target_: EasyNCO.phases.train.rl.nar_reinforce.REINFORCENARLightning
  problem_size: 120
  problem_type: 'bpp'
  batch_size: 20
  episodes: 200
  optimizer_params: {'optimizer': {
      'lr': 1e-4,
      'weight_decay': 1e-6
    },
    #    'scheduler': {
    #        'milestones': [501,],
    #        'gamma': 0.1
    #    }
  }
  policy_param: {'model_name': 'GNN',
               'n_ants': 20,
               'decay': 0.9,
               'alpha': 1,
               'beta': 1,
               'elitist': False,
  }

# The most important hyperparameter to use is `reload_dataloaders_every_n_epochs`.
# This allows for datasets to be re-created on the run and distributed by Lightning across
# devices on each epoch. Setting to a value different than 1 may lead to overfitting to a
# specific (such as the initial) data distribution.
trainer:
  _target_: EasyNCO.phases.train.rl.RLTrainer
  max_epochs: 5
  reload_dataloaders_every_n_epochs: 1
  log_every_n_steps: 1
  accelerator: 'gpu'
  num_nodes: 1 # Number of gpu nodes for distributed training

# https://www.tensorflow.org/tensorboard/
#Solve the error: ImportError: cannot import name ‘notf‘ from ‘tensorboard.compat‘
#Solution: Uninstall tensorflow and tensorboard(including all affiliated libraries)
# and only install tensorboard if you are using pytorch.
logger:
  _target_: lightning.pytorch.loggers.TensorBoardLogger
  save_dir: "tensorboard_log/"
  name: null
  log_graph: False
  default_hp_metric: True
  prefix: ""

model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: 'checkpoints_debug/'
  filename: 'deepaco-{epoch:02d}'
  save_top_k: -1
  every_n_epochs: 1

#custom_progressBar:
#  _target_: EasyNCO.phases.single_obj.CustomProgressBar

tester:
  _target_: EasyNCO.phases.eval.Evaluate_nar.EVALUATENARLightning

test_loader:
  problem_type: ${module.problem_type}
  problem_size: ${module.problem_size}
  # The output will be the result for the corresponding number of iterations.
  iteration: 10
  model_dirpath: "/DeepACO_pretrain/bpp/"
  model_filename: 'bpp120.pt'
  data_dict : {
                      use_customized_data : False,
                      data_path : "/data/datasets_deepaco/bpp/testDataset-120.pt"
  }
  test_params: {
                 'test_episodes' : 120,
                 'test_batch_size' : 12,
                 'test_strategy' : 'greedy',
                 'augmentation' : {
                                    'enable' : False,
                                    'aug_factor' : 1
                 },
                 'policy_param': {'model_name': 'GNN',
                                 'n_ants': 20,
                                 'decay': 0.9,
                                 'alpha': 1,
                                 'beta': 1,
                                 'elitist': False,
                                 'min_max': False,
                                 'min': null,
                 }
  }
