# @package _global_

defaults:
  - _self_

env:
  _target_: EasyNCO.methods.envs.TSPEnv
  problem_size: 500 # including 1 depot
  pomo_size: 60
  aug_factor: 8

model:
  _target_: EasyNCO.methods.operators.neural_operators.DPNPolicy
  env_name: "min-max mtsp"
  num_heads: 8
  qkv_dim: 16
  num_encoder_layers: 6
  feedforward_hidden: 512
  tanh_clipping: 50

module:
  _target_: EasyNCO.phases.train.rl.REINFORCELightning
  baseline: "shared"
  problem_size: ${env.problem_size}
  batch_size: 128
  episodes: 100
  first_mode: "random"
  aug_factor: ${env.aug_factor}
  optimizer_params:
    {
      "optimizer": { "lr": 1e-4, "weight_decay": 1e-6 },
      "scheduler": { "milestones": [501], "gamma": 0.1 },
    }
  test_strategy: "greedy"

logger:
  _target_: lightning.pytorch.loggers.TensorBoardLogger
  save_dir: "tensorboard_log/"
  name: null
  log_graph: False
  default_hp_metric: True
  prefix: ""

model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: "checkpoints_debug/"
  filename: "am-{epoch:02d}"
  save_top_k: -1 # save all checkpoints
  every_n_epochs: 1 # save it every epoch

trainer:
  _target_: EasyNCO.phases.train.rl.RLTrainer
  max_epochs: 5
  reload_dataloaders_every_n_epochs: 1
  log_every_n_steps: 1
  accelerator: "gpu"
  num_nodes: 1 # Number of gpu nodes for distributed training

test_loader:
  model_dirpath: "/methods/operators/neural_operators/dpn/pretrained/mtsp/"
  model_filename: "mtsp100.ckpt"
  data_path: "/data/datasets/mtsp/mtsp100_test_seed3333.pkl"
