# https://hydra.cc/docs/configure_hydra/intro/
env:
  _target_: EasyNCO.neural_solvers.envs.TSPEnv
  problem_size: ${scale}
  pomo_size: 1
  aug_type: pomo_aug # 'pomo_aug'/'rotate'/'reflect'/'mix'/'noise'
  aug_factor: 1
  use_graph: True
  env_name: ${problem}


model:
  _target_: EasyNCO.neural_solvers.methods.DIFUSCOPolicy
  env_name: ${problem}
  n_layers: 12
  hidden_dim: 256
  aggregation: 'sum'
  diffusion_type: 'gaussian' # option: mis: gaussian; tsp: categorical
  diffusion_schedule: 'linear' # option: cosin
  diffusion_steps: 1000
  sparse_factor: -1
  node_feature_only: True # True for mis
  use_activation_checkpoint: False
  parallel_sampling: 1 # to store the heatmap, must set to 1
  sequential_sampling: 1
  inference_diffusion_steps: 20
  inference_schedule: 'cosine' # option: linear
  inference_trick: 'ddim'

initialization:
  _target_: EasyNCO.neural_solvers.methods.DIFUSCOInitialization

iteration:
  _target_: EasyNCO.neural_solvers.methods.DIFUSCOIteration

module:
  _target_: EasyNCO.phases.ARREINFORCELightning
  problem: ${problem}
  method_name: ${model}
  baseline: null
  problem_size: ${scale}
  batch_size: ${batch_size}
  episodes: ${episodes}
  val_episode: ${val_episode}
  optimizer_type: 'Adam' # 'Adam', 'AdamW'
  scheduler_type: null #'ExponentialLR', 'MultiStepLR'
  optimizer_params: {
    'optimizer': {
        'lr': 1e-4,
        'weight_decay': 1e-6
    },
  }
  decoder_strategy: ${decoder_strategy}
  every_n_steps_output: 100 # output log every n steps (i.e., batch)
  initialization_params:
#    heatmap_path: '/phases/train/sl/heatmap/'
     heatmap_path: null
     
  iteration_params:
    max_steps: 10 # max steps for each episode, used for iteration
  train_data_params: {
                      'graph' : True,
  }
  test_data_params: {
                     'graph' : True,
  }


model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: checkpoints
  filename: ${model}_${problem}${scale}_{epoch:02d}
  save_top_k: ${save_top_k}
  every_n_epochs: ${every_n_epochs}

trainer:
  _target_: lightning.pytorch.Trainer
  max_epochs: ${max_epochs} # max epochs
  reload_dataloaders_every_n_epochs: 0 # RL: 1, SL: 0
  log_every_n_steps: ${log_every_n_steps} # log every n steps
  precision: ${precision}
  enable_progress_bar: ${enable_progress_bar} # disable progress bar
  gradient_clip_val: 1.0

test_loader:
  model_dirpath: pretrained # your path to the checkpoint
#  model_filename: ${model}_${problem}${scale}_epoch=04.ckpt
  model_filename: difusco_mis_er.ckpt
#  model_filename: tsp100_categorical.ckpt