# https://hydra.cc/docs/configure_hydra/intro/
env:
  _target_: EasyNCO.neural_solvers.envs.TSPEnv
  problem_size: ${scale}
  pomo_size: ${scale}
  aug_type: pomo_aug # 'pomo_aug'/'rotate'/'reflect'/'mix'/'noise'
  aug_factor: 1

model:
  _target_: EasyNCO.neural_solvers.methods.HTSPPolicy
  env_name: ${problem}
  Encoder:
    input_dim: 8
    embedding_dim: 128
  Actor:
    state_dim: 128
    mid_dim: 128
    action_dim: 2
    init_a_std_log: -1
  Critic:
    state_dim: 128
    mid_dim: 512
    _action_dim: 2
  low_level_type: 'pomo'
  low_level:
      low_level_buffer_size: 10000
      frag_len: 200
      node_dim: 2
      group_size: 200
      update_time: None
      # lower_path: '/h_tsp_ckpts/lower_level/lower200/best.ckpt'
      lower_path: '/pretrained/htsp_lower_tsp.ckpt'
  low_env:
    k: 40
    frag_len: 200
    max_new_nodes: 190
    max_improvement_step: 0
    auto_reset: False
    # training: True; eval: False
    no_depot: False

  target_step: 64
  reward_scale: 1.0
  gamma: 1.0
  experience_items: 6
  env_num: 64
  grad_method: norm
  lambda_GAE: 0.9
  data_augment: False

  eval:
    time_limit: 100.0
    batch_size: 16
    improvement_step: 0



initialization:
  _target_: EasyNCO.neural_solvers.methods.HTSPInitialization

iteration:
  _target_: EasyNCO.neural_solvers.pipeline.NoIteration

module:
  _target_: EasyNCO.phases.ARREINFORCELightning #
  method_name: ${model}
  baseline: 'shared'
  problem_size: ${scale}
  batch_size: ${batch_size}
  episodes: ${episodes}
  val_episode: ${val_episode}
  optimizer_type: 'Adam' # 'Adam', 'AdamW'
  scheduler_type: null #'ExponentialLR', 'MultiStepLR'
  optimizer_params: {
    'optimizer': {
        'lr': 1e-4,
        'weight_decay': 1e-6
    },
#    'scheduler': {
#        'milestones': [501,],
#        'gamma': 0.1
#    }
  }
  decoder_strategy: ${decoder_strategy}
  every_n_steps_output: 100 # output log every n steps (i.e., batch)

  repeat_times: 2
  grad_method: norm
  lambda_adv: 1.0
  clip_epsilon: 0.2
  lambda_entropy: 0.02
  lambda_aux: 0.05
  target_entropy_beta: 0.0002
  entropy_target: 0.2
  tau: 0.005
  grad_clip: 1
  low_level_train: False




model_checkpoint:
  #_target_: lightning.pytorch.callbacks.ModelCheckpoint
  _target_: EasyNCO.utils.utils.CustomModelCheckpoint
  dirpath: checkpoints
  filename: ${model}_${problem}${scale}_{epoch:02d}
  save_top_k: ${save_top_k}
  every_n_epochs: ${every_n_epochs}

trainer:
  _target_: lightning.pytorch.Trainer
  max_epochs: ${max_epochs} # max epochs
  reload_dataloaders_every_n_epochs: 1 # RL: 1, SL: 0
  log_every_n_steps: ${log_every_n_steps} # log every n steps
  precision: ${precision}
  enable_progress_bar: ${enable_progress_bar} # disable progress bar

test_loader:
  model_dirpath: pretrained/ # change
  model_filename: htsp_tsp${scale}.ckpt # change
