# https://hydra.cc/docs/configure_hydra/intro/
env:
  _target_: EasyNCO.neural_solvers.envs.TSPEnv
  problem_size: ${scale}
  pomo_size: ${scale}
  aug_type: pomo_aug # 'pomo_aug'/'rotate'/'reflect'/'mix'/'noise'
  method_name: ${model}
  aug_factor: 8

model:
  _target_: EasyNCO.neural_solvers.methods.ICAMPolicy
  env_name: ${problem}
  num_heads: 8
  qkv_dim: 16
  num_encoder_layers: 12
  normalization: 'instance' # 'batch', 'layer', 'instance' or null (i.e., None)
  feedforward_hidden: 512
  logit_clipping: 50
  use_graph_mean: False
  am_mode: False
  first_placeholder: False
  first_mode: 'random' # random or placeholder

initialization:
  _target_: EasyNCO.neural_solvers.methods.ICAMInitialization

iteration:
  _target_: EasyNCO.neural_solvers.pipeline.NoIteration

module:
  _target_: EasyNCO.phases.ARREINFORCELightning #
  method_name: ${model}
  baseline: 'shared'
  problem_size: ${scale}
  batch_size: ${batch_size}
  episodes: ${episodes}
  val_episode: ${val_episode}
  optimizer_type: 'Adam' # 'Adam', 'AdamW'
  scheduler_type: null #'ExponentialLR', 'MultiStepLR'
  optimizer_params: {
    'optimizer': {
        'lr': 1e-4,
        'weight_decay': 1e-6
    },
#    'scheduler': {
#        'milestones': [501,],
#        'gamma': 0.1
#    }
  }
  decoder_strategy: ${decoder_strategy}
  every_n_steps_output: 100 # output log every n steps (i.e., batch)

model_checkpoint:
  #_target_: lightning.pytorch.callbacks.ModelCheckpoint
  _target_: EasyNCO.utils.utils.CustomModelCheckpoint
  dirpath: checkpoints
  filename: ${model}_${problem}${scale}_{epoch:02d}
  save_top_k: ${save_top_k}
  every_n_epochs: ${every_n_epochs}

trainer:
  _target_: lightning.pytorch.Trainer
  max_epochs: ${max_epochs} # max epochs
  reload_dataloaders_every_n_epochs: 1 # RL: 1, SL: 0
  log_every_n_steps: ${log_every_n_steps} # log every n steps
  precision: ${precision}
  enable_progress_bar: ${enable_progress_bar} # disable progress bar
  gradient_clip_val: 1.0

test_loader:
  model_dirpath: pretrained
  model_filename: ${model}_${problem}_best.ckpt
