# https://hydra.cc/docs/configure_hydra/intro/
env:
  _target_: EasyNCO.neural_solvers.envs.TSPEnv
  problem_size: ${scale}
  pomo_size: 1
  aug_type: pomo_aug # 'pomo_aug'/'rotate'/'reflect'/'mix'/'noise'
  aug_factor: 1
  method_name: ${model}
  use_flag_to_indicate_depot: True

model:
  _target_: EasyNCO.neural_solvers.methods.LEHDPolicy
  env_name: ${problem}
  phase: ${mode}
  layer_num: 6
  node_dim: 2
  embed_dim: 128
  num_heads: 8
  qkv_dim: 16
  feedforward_hidden: 512
  normalization: None
  first_mode: 'random'

initialization:
  _target_: EasyNCO.neural_solvers.methods.LEHDInitialization

iteration:
  _target_: EasyNCO.neural_solvers.methods.LEHDIteration

module:
  _target_: EasyNCO.phases.ARREINFORCELightning
  method_name: ${model}
  baseline: 'shared'
  problem_size: ${scale}
  batch_size: ${batch_size}
  episodes: ${episodes}
  val_episode: ${val_episode}
  optimizer_type: 'Adam' # 'Adam', 'AdamW'
  scheduler_type: null #'ExponentialLR', 'MultiStepLR'
  optimizer_params: {
    'optimizer': {
        'lr': 1e-4,
        'weight_decay': 1e-6
    },
#    'scheduler': {
#        'milestones': [501,],
#        'gamma': 0.1
#    }
  }
  decoder_strategy: ${decoder_strategy}
  every_n_steps_output: 100 # output log every n steps (i.e., batch)
  iteration_params:
    max_steps: 10 # max steps for each episode, used for iteration

model_checkpoint:
  #_target_: lightning.pytorch.callbacks.ModelCheckpoint
  _target_: EasyNCO.utils.utils.CustomModelCheckpoint
  dirpath: checkpoints
  filename: ${model}_${problem}${scale}_{epoch:02d}
  save_top_k: ${save_top_k}
  every_n_epochs: ${every_n_epochs}

trainer:
  _target_: lightning.pytorch.Trainer
  max_epochs: ${max_epochs} # max epochs
  reload_dataloaders_every_n_epochs: 1 # RL: 1, SL: 0
  log_every_n_steps: ${log_every_n_steps} # log every n steps
  precision: ${precision}
  enable_progress_bar: ${enable_progress_bar} # disable progress bar
  gradient_clip_val: 1.0

test_loader:
  model_dirpath: pretrained
  model_filename: lehd_tsp100.ckpt
