# https://hydra.cc/docs/configure_hydra/intro/
env:
  _target_: EasyNCO.neural_solvers.envs.ATSPEnv
  problem_size: ${scale} # called node_cnt
  pomo_size: ${scale} # same as node_cnt
  aug_type: pomo_aug # 'pomo_aug'/'rotate'/'reflect'/'mix'/'noise'
  aug_factor: 8
  pos_embedding_dim:  512
  method_name: ${model}
  init_solver: nn

model:
  _target_: EasyNCO.neural_solvers.methods.MatPOENetPolicy
  embedding_dim: 512
  num_heads: 16
  qkv_dim: 16
  num_encoder_layers: 5
  logit_clipping: 10
  one_hot_seed_cnt: ${scale} # must be >= node_cnt
  ms_hidden_dim: 16
  feedforward_hidden: 512
  pos_embedding_dim:  512

initialization:
  _target_: EasyNCO.neural_solvers.methods.MatPOENetInitialization

iteration:
  _target_: EasyNCO.neural_solvers.pipeline.NoIteration

module:
  _target_: EasyNCO.phases.ARREINFORCELightning #
  method_name: ${model}
  baseline: 'shared'
  problem_size: ${scale}
  batch_size: ${batch_size}
  episodes: ${episodes}
  val_episode: ${val_episode}
  optimizer_type: 'Adam' # 'Adam', 'AdamW'
  scheduler_type: "MultiStepLR"
  optimizer_params: {
    'optimizer': {'lr': 1e-4, 'weight_decay': 1e-6},
    'scheduler': { "gamma": 0.1, "milestones": [2001, 2101] }
  }
  decoder_strategy: ${decoder_strategy}
  train_data_params: { "int_min": 0, "int_max": 1000000, "scaler": 1000000 }
  every_n_steps_output: 100 # output log every n steps (i.e., batch)

model_checkpoint:
  #_target_: lightning.pytorch.callbacks.ModelCheckpoint
  _target_: EasyNCO.utils.utils.CustomModelCheckpoint
  dirpath: checkpoints
  filename: ${model}_${problem}${scale}_{epoch:02d}
  save_top_k: ${save_top_k}
  every_n_epochs: ${every_n_epochs}

trainer:
  _target_: lightning.pytorch.Trainer
  max_epochs: ${max_epochs} # max epochs
  reload_dataloaders_every_n_epochs: 1 # RL: 1, SL: 0
  log_every_n_steps: ${log_every_n_steps} # log every n steps
  precision: ${precision}
  enable_progress_bar: ${enable_progress_bar} # disable progress bar
  gradient_clip_val: 1.0

test_loader:
  # model_dirpath: /results/train/pomo_tsp/2025-06-18-12-15-08_pomo_tsp_100_train/checkpoints
  # model_filename: ${model}_${problem}${scale}_epoch04.ckpt
  # EasyNCO/neural_solvers/methods/matpoenet/ckpts/MatNet-POE_mix.pt
  model_dirpath: pretrained/
  model_filename: MatNet-POE_mix.pt

